<?php

/**
 * Implement hook_menu() 
 */
function jagency_translate_menu() {
  $items = array();
  
  $items['admin/config/jagency/translate'] = array( 
    'title' => 'Jewish agency Translate Taxonomy', 
    'description' => '.', 
    'page callback' => 'jagency_translate_taxonomy_create', 
    'page arguments' => array('jagency_pages_admin_settings_form'), 
    'access arguments' => array('administer site configuration'), 
    'type' => MENU_NORMAL_ITEM, 
  );
  
  return $items;
}

function jagency_translate_taxonomy_create() {
  $vs = taxonomy_get_vocabularies();
  foreach ($vs as $v) {
    $terms = taxonomy_get_tree($v->vid);
    foreach ($terms as $term) {
      try {
        $result = db_insert('locales_source')->fields(array(
          'location' => 'taxonomy:term:'.$term->tid.':name',
          'textgroup' => 'taxonomy',
          'source' => $term->name,
          'context' => 'taxonomy:'.$term->tid.':name',
          'version' => 1
        ))->execute();
        
        $db = db_insert('locales_source')->fields(array(
          'location' => 'taxonomy:term:'.$term->tid.':description',
          'textgroup' => 'taxonomy',
          'source' => $term->description,
          'context' => 'taxonomy:'.$term->tid.':description',
          'version' => 1
        ))->execute();
      
      } catch(Exception $ex) {
        //d($ex);
      }
    }
  }
}