<?php

/**
 * Implements hook_features_api().
 */
function uuid_pathauto_features_api() {
  $components = array();

  $components['uuid_pathauto'] = array(
    'name' => t('Pathauto'),
    'feature_source' => TRUE,
    'default_hook' => 'uuid_features_default_pathauto',
    'default_file' => FEATURES_DEFAULTS_INCLUDED,
    'file' => drupal_get_path('module', 'uuid_pathauto') . '/includes/uuid_pathauto.features.inc',
  );
  
  return $components;
}