<?php

function jagency_domain_menu() {
  $items = array();

  $items['admin/config/jagency/affiliate'] = array( 
    'title' => 'Clear all send to all affiliates', 
    'description' => 'Set to 0 send to all affiliates.', 
    'page callback' => 'jagency_domain_clear_affiliates', 
    'access arguments' => array('administer site configuration'), 
    'type' => MENU_NORMAL_ITEM
  );
  
  return $items;
}

/**
 * Implements hook_menu_alter
 */
function jagency_domain_menu_alter(&$items) {
  $items['admin/structure/menu']['page callback'] = 'jagency_domain_menu_overview_page';
}

/**
 * Menu callback which shows an overview page of all the custom menus and their descriptions.
 */
function jagency_domain_menu_overview_page() {
  global $user;
  $menu_inuse = array();
  foreach($user->domain_user as $domain_id) {
    $menu_inuse[] = domain_conf_variable_get($domain_id, "menu_main_links_source");
    $menu_inuse[] = domain_conf_variable_get($domain_id, "menu_secondary_links_source");
    $menu_inuse[] = domain_conf_variable_get($domain_id, "menu_top_links_source");
  } 
  if (!in_array('administrator', $user->roles)) {
    $result = db_query("SELECT * FROM {menu_custom} WHERE menu_name IN ('".implode("','", $menu_inuse)."') ORDER BY title", array(), array('fetch' => PDO::FETCH_ASSOC));
  } else {
    $result = db_query("SELECT * FROM {menu_custom} ORDER BY title", array(), array('fetch' => PDO::FETCH_ASSOC));
  }
  $header = array(t('Title'), array('data' => t('Operations'), 'colspan' => '3'));
  $rows = array();
  foreach ($result as $menu) {
    $row = array(theme('menu_admin_overview', array('title' => $menu['title'], 'name' => $menu['menu_name'], 'description' => $menu['description'])));
    $row[] = array('data' => l(t('list links'), 'admin/structure/menu/manage/' . $menu['menu_name']));
    $row[] = array('data' => l(t('edit menu'), 'admin/structure/menu/manage/' . $menu['menu_name'] . '/edit'));
    $row[] = array('data' => l(t('add link'), 'admin/structure/menu/manage/' . $menu['menu_name'] . '/add'));
    $rows[] = $row;
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

function jagency_domain_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node_edit_form']) && $form['#node_edit_form'] == 1) {
    if (isset($form['domain'])) {
      //d($form_state);
      //unset($form['domain']['domain_site']['#default_value']);
      //d($form['domain']['domain_site']);
      unset($form['domain']['domain_site']);
      //$form['domain']['domain_site']['#default_value'] = 0;
    }
  }
  switch($form_id) {
    case 'views_exposed_form':
      if (isset($form['field_organizations_target_id'])) {
        foreach ($form['field_organizations_target_id']['#options'] as $key => $val) {
          if (is_numeric($key)) {
            $form['field_organizations_target_id']['#options'][$key] = jagency_taxonomy_translate($key, $val);
          }
        }
      }
      break;
    case 'domain_conf_form':
      $menuitems = array('domain-conf-ignore' => 'Use primary domain settings');
      $menuitems += menu_get_menus();
      $form['Menu settings']['menu_top_links_source'] = array(
        '#title' => 'Source for the Third Menu links',
        '#type' => 'select',
        '#options' => $menuitems,
        '#description' => 'Select the source for the Secondary links. An advanced option allows you to use the same source for both Main links (currently Main menu) and Secondary links: if your source menu has two levels of hierarchy, the top level menu links will appear in the Main links, and the children of the active link will appear in the Secondary links.',
        "#default_value" => domain_conf_variable_get($form['domain_id']['#value'], "menu_top_links_source")
      );
    break;
    
  }
}

function jagency_domain_clear_affiliates() {
  db_delete('domain_access')
    ->condition('realm', 'domain_site')
    ->condition('gid', 0)
    ->execute();
  //node_access_needs_rebuild(TRUE);
  drupal_set_message('Domain affiliates removed!');
  drupal_goto('admin/reports/status/rebuild');
  return;
}

function jagency_domain_get_current_tld($addslash = false) {
  $domain = domain_get_domain();
  $domains_tld = substr($domain['subdomain'], 0, strpos($domain['subdomain'], '.'));
  $tld = '';
  if ($domains_tld != 'www') {
    $tld = $domains_tld . '/';
  }
  if ($addslash) {
    $tld = '/' . $tld;
  }
  return $tld;
}
