<?php
/*
 * Implementation hook_views_api()
 */
function views_taxonomylocalize_views_api() {
  return array(
    'api' => 3,
  );
}

/*
 * Implementation of hook_views_pre_render(&$view)
 */
function views_taxonomylocalize_views_pre_render(&$view) {
  global $language;

  foreach($view->result as $delta => $term ){
 	if(isset($term->tid)) {

	  i18n_string_translate_langcode( $language->language );
	  $localized_term = i18n_taxonomy_localize_terms( taxonomy_term_load( $term->tid ));
	  $term->tid = $localized_term->tid;
	  $term->taxonomy_term_data_name = $localized_term->name;
	}
  }
}