<?php

/**
 * @file
 *   Implements a views row plugin that can display the first nodes in a result
 * using a different view mode.
 */

/**
 * Implements hook_views_plugins().
 */
function views_user_split_views_plugins() {
  return array(
    'module' => 'views', // This just tells our themes are elsewhere.
    'row' => array(
      'user_split' => array(
        'title' => t('Splited user content'),
        'help' => t('Display the content with standard node view, but the first nodes can have different view modes.'),
        'handler' => 'views_plugin_row_user_view_split',
        'path' => drupal_get_path('module', 'views_user_split') . '/plugins',
        'uses options' => TRUE,
        'type' => 'normal',
        //'parent' => 'views_plugin_row_user_view',
      )
    ),
    'argument validator' => array(
      'user' => array(
        'title' => t('User Content'),
        'handler' => 'views_plugin_argument_validate_node',
      ),
    ),
    'argument default' => array(
      'user' => array(
        'title' => t('User ID from URL'),
        'handler' => 'views_plugin_argument_default_node'
      ),
    ),
  );
}